apiVersion: v1
kind: Pod
metadata:
  name: gpu-burn
spec:
  restartPolicy: OnFailure
  containers:
  - name: gpu-burn
    image: "quay.io/trent_s/gpu-burn"
    env:
    - name: RUNSECONDS
      value: 60
    resources:
      limits:
        nvidia.com/gpu: 1
