apiVersion: v1
kind: Pod
metadata:
  name: gpu-burn
spec:
  restartPolicy: OnFailure
  containers:
  - name: gpu-burn
    image: "quay.io/trent_s/gpu-burn"
    resources:
      limits:
        nvidia.com/gpu: 1
